name: Maven Deploy

on:
  push:
    branches:
      - main # or your default branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Deploy with Maven
        run: mvn deploy --settings .mvn/settings.xml
        env:
          JOOQ_REPO_USERNAME: ${{ secrets.JOOQ_REPO_USERNAME }}
          JOOQ_REPO_PASSWORD: ${{ secrets.JOOQ_REPO_PASSWORD }}